### ISSUE TITLE
emulator.exe path

### ISSUE THREAD

**Issue by SynapseScribe** [enieber/open-avd#4]
emulator resides on C:\Users\<user>\AppData\Local\Android\Sdk\emulator on latest versions, not on tools

should change to:
...
pushd ${ANDROID_HOME}/emulator
...

**Comment by enieber** [comment]
@fusionneur  thanks to you verify. I don't use more windows, so if you wanna change and open pull request is welcome..

**Comment by SynapseScribe** [comment]
pushd ${ANDROID_HOME}/emulator instead of 
pushd ${ANDROID_HOME}/tools
,where ${ANDROID_HOME} is  /home/<user>/Android/Sdk/

I tested both stable (electric eel) and canary (giraffe) version of Android Studio.

PR: https://github.com/enieber/open-avd/pull/5

**Comment by enieber** [comment]
thanks @fusionneur
